import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

export interface UpdateReadmeOptions {
  projectRoot: string;
  appName: string;
  destinationName: string;
  assetPath: string;
}

const MARKER_PATTERN = /<!-- honeypie:start -->[\s\S]*?<!-- honeypie:end -->/;

/** Idempotently patches (or inserts) the HoneyPie preview block in the project README. */
export async function updateReadme(options: UpdateReadmeOptions): Promise<void> {
  const readmePath = join(options.projectRoot, "README.md");
  const existing = await readTextIfExists(readmePath);
  const base = existing ?? `# ${options.appName}\n`;
  const imagePath = `${options.destinationName}/${options.assetPath}`.replace(/\\/g, "/");
  const block = [
    "<!-- honeypie:start -->",
    "## App Preview",
    "",
    `![${options.appName} app mockup](${imagePath})`,
    "",
    "_Generated by HoneyPie._",
    "<!-- honeypie:end -->"
  ].join("\n");
  const next = MARKER_PATTERN.test(base) ? base.replace(MARKER_PATTERN, block) : appendReadmeBlock(base, block);
  await writeFile(readmePath, ensureTrailingNewline(next));
}

function appendReadmeBlock(readme: string, block: string): string {
  return `${readme.trimEnd()}\n\n${block}`;
}

function ensureTrailingNewline(value: string): string {
  return value.endsWith("\n") ? value : `${value}\n`;
}

async function readTextIfExists(path: string): Promise<string | null> {
  try {
    return await readFile(path, "utf8");
  } catch (error) {
    if (error && typeof error === "object" && "code" in error && error.code === "ENOENT") return null;
    throw error;
  }
}
